In [82]:
##Import Libraries
import pandas as pd

In [83]:
dataset=pd.read_csv("splitTrain.csv", engine='python', error_bad_lines=False)

/var/folders/47/rvf0d45n2fx2z6syh12kr0s40000gn/T/ipykernel_1615/617442921.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  dataset=pd.read_csv("splitTrain.csv", engine='python', error_bad_lines=False)
Skipping line 2503: unexpected end of data


In [84]:
dataset.head(130)

ImgId                                              title  \
0    B000HYL1V6                   TUNGSTEN SOLDER PICK WITH HANDLE   
1    B00006HXWY  Write Right 98167 Screen Protector for Sony T615C   
2    B000GAWSBS  Casio Mens DBC310-1 Databank 300 Digital Watch...   
3    B000040JOL  Factory-Reconditioned DEWALT DW260KR Heavy-Dut...   
4    B00006IB78                             Energizer 2 in 1 Light   
..          ...                                                ...   
125  B000VFNJC0  OCZ OCZMSEQRD Desktop Size Equalizer Laser Gam...   
126  B002HTPD5O  Tooth Fairy Pillow (self-contained pillow) - A...   
127  1589780817                              Unhappy Homes (Gloom)   
128  B0002AT590                      Petmate Indigo Dog House Door   
129  B0002AR2DQ                          Booda Wing-A-Ball Dog Toy   

                                           description  \
0    Solder Pick for picking up molten solder when ...   
1    We all screen. And we all need to protect thos...   
2    Bringing you precision at a glance, the Casio ...   
3    Factory-Reconditioned DEWALT DW260KR Heavy-Dut...   
4    This twoway light features a bright flashlight...   
..                                                 ...   
125  OCZ Equalizer laser gaming mouse is sure to ex...   
126  Our Personalized Tooth Fairy Pillows are made ...   
127  In the Gloom card game, you make your eccentri...   
128  What We Like About the Petmate Indigo Dog Hous...   
129  The BOODA Wing-a-Ball is a great interactive t...   

                    categories  
0        Arts, Crafts & Sewing  
1    Cell Phones & Accessories  
2    Clothing, Shoes & Jewelry  
3     Tools & Home Improvement  
4       Health & Personal Care  
..                         ...  
125            All Electronics  
126              Baby Products  
127               Toys & Games  
128               Pet Supplies  
129               Pet Supplies  

[130 rows x 4 columns]

In [85]:
dataset.shape

(2501, 4)

In [86]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2501 entries, 0 to 2500
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   ImgId        2501 non-null   object
 1   title        2501 non-null   object
 2   description  2460 non-null   object
 3   categories   2501 non-null   object
dtypes: object(4)
memory usage: 78.3+ KB


Only stars and score are in float rest are objects

In [88]:
def important_features(dataset):
    data=dataset.copy()
    for i in range(0, dataset.shape[0]):
        data["imp"]=data["title"]+' '+data["description"]+" "+data["categories"]
    return data


In [89]:
data=important_features(dataset)

In [90]:
data.head(20)

ImgId                                              title  \
0   B000HYL1V6                   TUNGSTEN SOLDER PICK WITH HANDLE   
1   B00006HXWY  Write Right 98167 Screen Protector for Sony T615C   
2   B000GAWSBS  Casio Mens DBC310-1 Databank 300 Digital Watch...   
3   B000040JOL  Factory-Reconditioned DEWALT DW260KR Heavy-Dut...   
4   B00006IB78                             Energizer 2 in 1 Light   
5   B000V9KD70                           Ducky Money Savings Bank   
6   B000YOUIN6                    Lilypadz Reuseable Nursing Pads   
7   B000EIEWCU                               Inglesina Twin Swift   
8   B0000CAQ0S  Eastman Outdoors 37206 Outdoor Gourmet 18-Inch...   
9   B000FTD1RA  DaVinci Elizabeth II Convertible Toddler Bed i...   
10  B000H8KGZ4                             Shaggy Costume - Large   
11  B00005MA7O                    Conair Shiny Multi-Plate Styler   
12  B000BTECFE  Florida State University Accessory Cover - Mar...   
13  B0000A1ANQ  MLB Boston Red Sox Pinch Hitter Wool Replica A...   
14  B00004TS3E  Brother 1 Inch x 26.2 Feet Red on White for P-...   
15  B0057V4W9M  VGA to HDMI With Audio Converter Plus AGPtek U...   
16  B0002MBUPA  WeatherTech All-Weather Trim to Fit Rear Rubbe...   
17  B00020T4UK  Verbatim DVD-R 4.7GB 8X DataLifePlus White Ink...   
18  B0002RNRZ6       Red R Racing Universal-Fit Bucket Seat Cover   
19  B000052Y6V  Top Brass Creme Formula Hairgroom for Men 3.3 ...   

                                          description  \
0   Solder Pick for picking up molten solder when ...   
1   We all screen. And we all need to protect thos...   
2   Bringing you precision at a glance, the Casio ...   
3   Factory-Reconditioned DEWALT DW260KR Heavy-Dut...   
4   This twoway light features a bright flashlight...   
5   This adorable ducky makes the perfect gift for...   
6   Lilypadz are the revolutionary alternative to ...   
7   Light weight double stroller that is perfect f...   
8   Eastman Outdoors offers High-Quality cooking p...   
9   This toddler bed is for your little king or qu...   
10  Item Sizing: The size guide found below is spe...   
11  Give your hair total range with the Conair CS9...   
12  Britax(R) is excited to announce the launch of...   
13  Founded in 1920, the New Era Cap Company is th...   
14  Find out which tapes are compatible with your ...   
15  Features:1. Supports VGA Video + L/R Audio inp...   
16  "These rear mats are designed to be trimmed or...   
17  Combining an exceptional inkjet hub-printable ...   
18  PlastiColor Red R Racing Universal-Fit Bucket ...   
19  Non-greasy control for a man's hair. Makes it ...   

                   categories  \
0       Arts, Crafts & Sewing   
1   Cell Phones & Accessories   
2   Clothing, Shoes & Jewelry   
3    Tools & Home Improvement   
4      Health & Personal Care   
5               Baby Products   
6               Baby Products   
7                        Baby   
8        Patio, Lawn & Garden   
9                        Baby   
10  Clothing, Shoes & Jewelry   
11                     Beauty   
12                       Baby   
13          Sports & Outdoors   
14                Electronics   
15            All Electronics   
16                 Automotive   
17            All Electronics   
18                 Automotive   
19                     Beauty   

                                                  imp  
0   TUNGSTEN SOLDER PICK WITH HANDLE Solder Pick f...  
1   Write Right 98167 Screen Protector for Sony T6...  
2   Casio Mens DBC310-1 Databank 300 Digital Watch...  
3   Factory-Reconditioned DEWALT DW260KR Heavy-Dut...  
4   Energizer 2 in 1 Light This twoway light featu...  
5   Ducky Money Savings Bank This adorable ducky m...  
6   Lilypadz Reuseable Nursing Pads Lilypadz are t...  
7   Inglesina Twin Swift Light weight double strol...  
8   Eastman Outdoors 37206 Outdoor Gourmet 18-Inch...  
9   DaVinci Elizabeth II Convertible Toddler Bed i...  
10  Shaggy Costume - Large Item Sizing: The size g.

In [91]:
data["ids"]=[i for i in range(0,data.shape[0])]

In [92]:
data["ids"].head(10000)

0          0
1          1
2          2
3          3
4          4
        ... 
2496    2496
2497    2497
2498    2498
2499    2499
2500    2500
Name: ids, Length: 2501, dtype: int64

In [31]:
##Importing vectoriser

In [93]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
vec=TfidfVectorizer()

In [94]:
vecs=vec.fit_transform(data["imp"].apply(lambda x: np.str_(x)))

In [95]:
vecs.shape

(2501, 22066)

In [96]:
print (vecs)

  (0, 17688)	0.12608906084992264
  (0, 6248)	0.12562357795961007
  (0, 3136)	0.12562357795961007
  (0, 11576)	0.13170716218936768
  (0, 12707)	0.14176619304441102
  (0, 21548)	0.10845748727179386
  (0, 13375)	0.24994753482242674
  (0, 20797)	0.0955222320579737
  (0, 15073)	0.24064087515046068
  (0, 9113)	0.04883720214028806
  (0, 10208)	0.13586799902250588
  (0, 21698)	0.05226241297644793
  (0, 15071)	0.38046822684234444
  (0, 18360)	0.7498426044672802
  (0, 20502)	0.2079150770894076
  (1, 2343)	0.08387152888511507
  (1, 15018)	0.09142309413943725
  (1, 5014)	0.08696758763989358
  (1, 8703)	0.1527383563395398
  (1, 20841)	0.10237387769154319
  (1, 10982)	0.038057592489064075
  (1, 21318)	0.10713108961467131
  (1, 22001)	0.05399421716347066
  (1, 2955)	0.13283916331076193
  (1, 8885)	0.08879363053395586
  :	:
  (2499, 20797)	0.050062850821372386
  (2499, 9113)	0.025595398187498276
  (2500, 3607)	0.21489405570440737
  (2500, 11506)	0.21489405570440737
  (2500, 3726)	0.3974543676535869
  

In [97]:
from sklearn.metrics.pairwise import cosine_similarity

In [98]:
sim=cosine_similarity(vecs) 

In [99]:
sim.shape##Columns represent ids and not rows

(2501, 2501)

In [100]:
print (sim)

[[1.         0.00663693 0.0097939  ... 0.00190226 0.00603212 0.07655307]
 [0.00663693 1.         0.03946996 ... 0.00919911 0.03174541 0.01024917]
 [0.0097939  0.03946996 1.         ... 0.00530049 0.04672148 0.01262955]
 ...
 [0.00190226 0.00919911 0.00530049 ... 1.         0.01250839 0.00298012]
 [0.00603212 0.03174541 0.04672148 ... 0.01250839 1.         0.01181702]
 [0.07655307 0.01024917 0.01262955 ... 0.00298012 0.01181702 1.        ]]


In [101]:
product_id=data[data.title=="Energizer 2 in 1 Light"]["ids"].values[0]
print (product_id)

4


In [102]:
scores=list(enumerate(sim[4]))
sorted_scores=sorted(scores,key=lambda x:x[1],reverse=True)
sorted_scores=sorted_scores[1:]

print (sorted_scores)

[(395, 0.1560155890395987), (102, 0.13727369612986118), (623, 0.1349159291071577), (1575, 0.1319865378597646), (2239, 0.12773252710655142), (735, 0.12478297353140103), (1281, 0.12415332345464662), (1056, 0.11895343643395208), (2231, 0.11693619292585915), (190, 0.11271848325492088), (1217, 0.10920252819523521), (1494, 0.10261918235859892), (1732, 0.09943633684425154), (2194, 0.09894969313125675), (639, 0.09584886736985773), (1729, 0.09338309411038095), (1059, 0.09238889984213117), (2077, 0.09221442232491253), (1963, 0.09099939850226982), (1420, 0.08950522490516001), (2432, 0.08934573909055396), (2234, 0.08634582426468485), (195, 0.0861778691753604), (1043, 0.08600051977686576), (2470, 0.08595936095265562), (1950, 0.08556455045152798), (1374, 0.08358113524841276), (1426, 0.08287778500651112), (7, 0.08198238018244795), (2033, 0.08178244473933763), (1054, 0.07935096195711826), (1071, 0.07917007438232652), (1238, 0.07859318330399974), (1087, 0.07843408965661904), (1710, 0.07802810995748118)

In [103]:
# print(data["categories"][5])
# print ((data[products[0]==data["ids"]]["categories"].values[0])==data["categories"][product_id])
# print (data["categories"][product_id])

Baby Products


NameError: name 'products' is not defined

In [104]:
for products in sorted_scores:
    {
        print (products[0])
        }


395
102
623
1575
2239
735
1281
1056
2231
190
1217
1494
1732
2194
639
1729
1059
2077
1963
1420
2432
2234
195
1043
2470
1950
1374
1426
7
2033
1054
1071
1238
1087
1710
1237
2342
200
357
1356
2251
569
2242
199
127
2494
711
625
2244
1600
1556
1080
1619
1901
1000
1936
2408
1654
2411
2245
1160
2007
2455
807
1444
587
11
2489
874
1176
653
741
194
1974
1125
2
1246
1581
328
2438
1391
294
2343
803
39
157
991
2165
1878
618
1583
411
855
1991
131
671
994
403
1975
1446
1808
1088
1232
737
220
892
1594
1053
69
1052
1871
1689
1030
2119
1747
1471
33
1157
2067
1629
462
1428
952
1443
2379
1106
795
1968
847
448
405
1514
2383
2016
2299
297
2161
2474
2405
1064
373
644
1493
2396
2265
2483
1733
1274
2087
1700
2419
485
2055
913
226
1166
1174
1042
139
2325
875
1812
2122
2023
1867
1595
1090
1259
1138
1276
471
869
165
362
218
1545
544
1075
2425
452
2202
305
924
82
2313
1411
2213
2074
705
2082
918
368
1870
2309
910
2266
1389
2444
1859
472
124
1384
2101
56
1436
1433
1923
2310
1346
2240
288
2160
870
826
356
1757
1423
1

In [105]:
# data[data.Name=="The Matrix"].ids.values[0]

AttributeError: 'DataFrame' object has no attribute 'Name'

In [106]:
def recommend(title):
    product_id=data[data.title==title]["ids"].values[0]
    print("product_id", product_id)
    scores=list(enumerate(sim[product_id]))
  #  print("scores", scores)
    sorted_scores=sorted(scores,key=lambda x:x[1],reverse=True)
   # print("sorted_scores", sorted_scores)
    sorted_scores=sorted_scores[1:]
    # categoryproducts = 
    
    # categoryproducts=[data[products[0]==data["ids"]]["categories"].values[0] for products in sorted_scores]
    # categoryproduct = [data[tempt[0]==data["categories"][product_id]]["title"].values[0] for tempt in categoryproducts]
    sorted_Score_By_Categories = []
    for products in sorted_scores:
      catogoryEachProduct = data[products[0]==data["ids"]]["categories"].values[0]   
      if catogoryEachProduct == data["categories"][product_id]:
        sorted_Score_By_Categories.append (products)
    sorted_Title=[data[products[0]==data["ids"]]["title"].values[0] for products in sorted_Score_By_Categories]      
    return sorted_Title

In [107]:
def recommend_ten(product_list):
    first_ten=[]
    count=0
    for product in product_list:
        if count > 9:
            break
        count+=1
        first_ten.append(product)
    return first_ten

In [108]:
lst=recommend("Energizer 2 in 1 Light")
#print ("lst", lst)
m=recommend_ten(lst)

product_id 4


In [109]:
m

['Emjoi AP-81 Dentapure Toothbrush Sanitizer',
 'Natural Contours Ultime Vibrator, Periwinkle Blue',
 'Lumiscope 1090 Desktop Blood Pressure Monitor',
 'Conair MBTS3 Thermal Spa Bathmat Bubble Massager',
 'Conair LWDHLD1 Grooming Gift Pack for Her',
 'Dorcy 41-1540 12AA Mastercell Heavy Duty Batteries',
 'Almay Roll-On Antiperspirant &amp; Deodorant, Unscented - 1.5 fl oz',
 'Ultrasonex Personal Touch 3 Brush Functions',
 'Wahl Attachment Combs 8-pk.',
 'Rubbermaid(R) Lobby Dustpan']